import {Dimensions, Platform, StyleSheet} from 'react-native';
import {FONTS, SIZES, COLORS} from '../../constant';
const width = Dimensions.get('screen').width;
export default styles = StyleSheet.create({
  row: {
    padding: SIZES.base,
    backgroundColor: COLORS.card_color,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: SIZES.base * 1.8,
  },

  locationText: {
    color: '#333333',
    ...FONTS.Regular10,
  },

  accordianButton: {
    paddingHorizontal: SIZES.padding2,
    paddingVertical: SIZES.base,
    borderRadius: SIZES.base,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
  },
  mapText: {
    color: COLORS.light_text_color,
    ...FONTS.Regular9,
    marginRight: SIZES.small / 2,
  },
  flexView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: SIZES.base * 2,
  },
  imageView: {
    height: SIZES.h52,
    width: SIZES.h52,
    borderRadius: SIZES.base * 2,
    backgroundColor: COLORS.card_color,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  img: {
    width: SIZES.h22,
    height: SIZES.h22,
  },
  lineImg: {
    flex: 1,
    marginHorizontal: SIZES.small,
  },
  text: {
    color: COLORS.light_text_color,
    ...FONTS.Regular10,
    paddingTop: SIZES.small,
  },
  row2: {
    alignItems: 'center',
  },
  detailView: {
    padding: SIZES.base * 2,
    backgroundColor: COLORS.card_color,
    borderRadius: SIZES.base * 1.8,
    height: 173,
    justifyContent: 'center',
  },
  commonView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: SIZES.padding,
  },
  detailsText: {
    color: COLORS.light_text_color,
    ...FONTS.Regular12,
  },
  expireText: {
    color: COLORS.light_text_color,
    ...FONTS.Regular9,
  },
  expireText2: {
    color: COLORS.white,
    ...FONTS.Medium13,
  },
  icons: {
    width: SIZES.h20,
    height: SIZES.h20,
    marginRight: SIZES.padding2,
  },
  flex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  statusView: {
    width: '40%',
    height: 25,
    alignItems: 'center',

    justifyContent: 'center',
    backgroundColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    borderRadius: SIZES.base,
  },
  statusText: {
    color: COLORS.primary,
    ...FONTS.Medium10,
    textTransform: 'uppercase',
  },
  statusText2: {
    color: COLORS.text_color,
    ...FONTS.Regular10,
  },
  buttonView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: SIZES.padding2,
    borderBottomColor: COLORS.card_color,
    borderBottomWidth: 1.5,
  },
  commonButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: SIZES.small,
    backgroundColor: COLORS.enabled,
    width: '60%',
    height: SIZES.h40,
  },
  commonButton2: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.enabled,
    height: SIZES.h40,
    flex: 1,
  },
  commonText: {
    color: COLORS.white,
    ...FONTS.SemiBold12,
  },
  buttonIcon: {
    width: SIZES.h20,
    height: SIZES.h20,
    marginRight: SIZES.medium,
  },
  commonCardText: {
    color: COLORS.black,
    ...FONTS.Medium15,
  },
  lighText: {
    color: COLORS.light_text_color,
    ...FONTS.Medium15,
  },
  lighText2: {
    color: COLORS.light_text_color,
    ...FONTS.Regular13,
  },
  messageText: {
    color: COLORS.light_text_color,
    ...FONTS.Regular9_5,
    paddingVertical: SIZES.small,
  },
  scrollButton: {
    padding: SIZES.base,
    backgroundColor: COLORS.card_color,
    borderRadius: SIZES.base,
  },
  commonCardView: {
    paddingVertical: SIZES.large,
    paddingBottom: SIZES.base,
    borderBottomColor: COLORS.card_color,
    borderBottomWidth: 1.5,
  },
  card: {
    backgroundColor: COLORS.card_color,
    borderRadius: SIZES.base * 2,
    marginVertical: SIZES.base,
    width: width - SIZES.h30 * 1.1,
    marginRight: SIZES.base,
    overflow: 'hidden',
  },
  driverProfile: {
    width: SIZES.h35,
    height: SIZES.h35,
  },
  transportTypeText: {
    color: COLORS.primary,
    textDecorationColor: COLORS.primary,
    textDecorationLine: 'underline',
    ...FONTS.Medium14,
    marginRight: SIZES.medium,
  },
  varifiedIcon: {
    width: SIZES.h17,
    height: SIZES.h17,
  },
  transportView: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingLeft: 16,
  },
  ratingView: {
    width: SIZES.h57,
    height: SIZES.h25,
    justifyContent: 'center',
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderRadius: SIZES.padding * 1.2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    ...FONTS.Regular11,
    color: COLORS.primary,
    marginLeft: SIZES.small,
  },
  postedText: {
    ...FONTS.Regular11,
    paddingVertical: SIZES.small,
    color: '#9CA0AC',
    marginLeft: SIZES.small,
    alignSelf: 'flex-end',
  },
  ratingIcon: {
    width: SIZES.h15,
    height: SIZES.h15,
    bottom: 2,
  },
  firstView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: SIZES.h10,
    borderBlockColor: '#C2C2C2',
    borderBottomWidth: 1,
    borderStyle: Platform.OS === 'android' ? 'dashed' : 'solid',
  },
  moreText: {
    color: COLORS.primary,
    textDecorationColor: COLORS.primary,
    textDecorationLine: 'underline',
    ...FONTS.Regular10,
  },

  bookNowButton: {
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    width: '35%',
    bottom: SIZES.padding2,
    right: SIZES.base,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    borderRadius: SIZES.base * 1.5,
    height: SIZES.h40,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  bookNowText: {
    color: COLORS.white,
    ...FONTS.Medium13,
    marginLeft: SIZES.base,
  },
  expireView: {
    backgroundColor: COLORS.black,
    opacity: 0.85,
    alignItems: 'center',
    paddingHorizontal: SIZES.base * 2,
    borderTopEndRadius: SIZES.h30,
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    alignItems: 'center',
  },
  vahicleImage: {
    height: 100,
    width: 180,
  },
  vahicleImage2: {
    height: SIZES.h30,
    width: SIZES.h30,
  },
  vehicleNumberText: {
    color: COLORS.black,
    ...FONTS.Medium16,
  },
  scrollView: {
    position: 'absolute',
    width: '100%',
    top: '20%',
    zIndex: 9999,
  },
  statusView2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '60%',
  },
  commonIcon: {marginRight: 10},
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  locationText2: {
    ...FONTS.Regular10,
    color: COLORS.text_color,
  },
});
